/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountRead { 
    id: string;
    supabase_user_id: string;
    email: string | null;
    display_name: string | null;
    avatar_url: string | null;
    profile_customized: boolean;
    providers: Array<string>;
    is_active: boolean;
    last_seen_at: string | null;
    created_at: string;
    updated_at: string;
}

