/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FieldError { 
    /**
     * Path to the field, e.g. [\'body\', \'name\'].
     */
    location: Array<string>;
    /**
     * What is wrong with it.
     */
    message: string;
    /**
     * Machine-readable failure kind.
     */
    type: string;
}

