/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InternalServerError { 
    error: InternalServerError.ErrorEnum;
    message: string;
}
export namespace InternalServerError {
    export const ErrorEnum = {
        InternalServerError: 'internal_server_error'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


