/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvalidBearerTokenError { 
    error: InvalidBearerTokenError.ErrorEnum;
    message: string;
}
export namespace InvalidBearerTokenError {
    export const ErrorEnum = {
        InvalidBearerToken: 'invalid_bearer_token'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


