/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MemberCreateError { 
    error: MemberCreateError.ErrorEnum;
    message: string;
}
export namespace MemberCreateError {
    export const ErrorEnum = {
        MemberCreateError: 'member_create_error'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


