/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MembersLoadError { 
    error: MembersLoadError.ErrorEnum;
    message: string;
}
export namespace MembersLoadError {
    export const ErrorEnum = {
        MembersLoadError: 'members_load_error'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


