/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MemberLoadError { 
    error: MemberLoadError.ErrorEnum;
    message: string;
}
export namespace MemberLoadError {
    export const ErrorEnum = {
        MemberLoadError: 'member_load_error'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


