/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MemberNotFoundError { 
    error: MemberNotFoundError.ErrorEnum;
    message: string;
}
export namespace MemberNotFoundError {
    export const ErrorEnum = {
        MemberNotFound: 'member_not_found'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


