/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MemberUpdateError { 
    error: MemberUpdateError.ErrorEnum;
    message: string;
}
export namespace MemberUpdateError {
    export const ErrorEnum = {
        MemberUpdateError: 'member_update_error'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


