/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MethodNotAllowedError { 
    error: MethodNotAllowedError.ErrorEnum;
    message: string;
}
export namespace MethodNotAllowedError {
    export const ErrorEnum = {
        Http405: 'http_405'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


