/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MissingBearerTokenError { 
    error: MissingBearerTokenError.ErrorEnum;
    message: string;
}
export namespace MissingBearerTokenError {
    export const ErrorEnum = {
        MissingBearerToken: 'missing_bearer_token'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


