/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemberUpdateError } from './member-update-error';
import { MemberLoadError } from './member-load-error';


/**
 * @type Response503Updatemember
 * @export
 */
export type Response503Updatemember = MemberLoadError | MemberUpdateError;

