/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MissingBearerTokenError } from './missing-bearer-token-error';
import { InvalidBearerTokenError } from './invalid-bearer-token-error';


/**
 * @type Response401Getmyaccount
 * @export
 */
export type Response401Getmyaccount = InvalidBearerTokenError | MissingBearerTokenError;

