/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RouteNotFoundError { 
    error: RouteNotFoundError.ErrorEnum;
    message: string;
}
export namespace RouteNotFoundError {
    export const ErrorEnum = {
        Http404: 'http_404'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


