/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UnauthenticatedRoleError { 
    error: UnauthenticatedRoleError.ErrorEnum;
    message: string;
}
export namespace UnauthenticatedRoleError {
    export const ErrorEnum = {
        UnauthenticatedRole: 'unauthenticated_role'
    } as const;
    export type ErrorEnum = typeof ErrorEnum[keyof typeof ErrorEnum];
}


