"""What the geocoder has already been asked, and what it answered.

The corpus is regenerated by re-scraping rather than preserved, so this cache is
what stops a re-scrape re-asking for every address it resolved last time. It
outlives the Listings whose addresses filled it, which is why it is keyed on the
normalised query rather than on a Listing.

The module is otherwise empty for now: the client that reads and fills this
lands with the geocoding work. The table is declared here rather than in
`events` because it is geocoding's to own - `events` will be one caller of it,
and the points-of-interest work another.
"""

from datetime import datetime

from sqlalchemy import DateTime, Float, Integer, Text, text
from sqlalchemy.orm import Mapped, mapped_column

from ...db.base import CONTENT_SCHEMA, Base


class GeocodeCache(Base):
    __tablename__ = "geocode_cache"
    __table_args__ = ({"schema": CONTENT_SCHEMA},)

    # The address as asked, casefolded and whitespace-collapsed, so two Sources
    # spelling one address differently still hit the same row.
    query_norm: Mapped[str] = mapped_column(Text, primary_key=True)
    query_raw: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Null when the geocoder had no answer. A cached miss is worth as much as a
    # cached hit: the next run must not ask again.
    lat: Mapped[float | None] = mapped_column(Float, nullable=True)
    lon: Mapped[float | None] = mapped_column(Float, nullable=True)
    precision: Mapped[str | None] = mapped_column(Text, nullable=True)

    provider: Mapped[str | None] = mapped_column(Text, nullable=True)
    raw_response: Mapped[str | None] = mapped_column(Text, nullable=True)
    geocoded_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # How often this address has been asked for and not found - the ranking for
    # deciding which addresses are worth fixing by hand.
    miss_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
