"""create meetups and meetup participants

Revision ID: 1e569d8570b6
Revises: bc2b6ec38063
Create Date: 2026-08-07 17:32:42.239166

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e569d8570b6"
down_revision: str | Sequence[str] | None = "bc2b6ec38063"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["accounts.id"],
            name=op.f("fk_meetups_created_by_account_id_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetups")),
    )
    op.create_index(
        op.f("ix_meetups_created_by_account_id"),
        "meetups",
        ["created_by_account_id"],
        unique=False,
    )
    op.create_table(
        "meetup_participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("meetup_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("created_by_account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("travel_mode", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_meetup_participants_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["accounts.id"],
            name=op.f("fk_meetup_participants_created_by_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["meetup_id"],
            ["meetups.id"],
            name=op.f("fk_meetup_participants_meetup_id_meetups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetup_participants")),
    )
    op.create_index(
        op.f("ix_meetup_participants_account_id"),
        "meetup_participants",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meetup_participants_created_by_account_id"),
        "meetup_participants",
        ["created_by_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meetup_participants_meetup_id"),
        "meetup_participants",
        ["meetup_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_meetup_participants_meetup_id"), table_name="meetup_participants"
    )
    op.drop_index(
        op.f("ix_meetup_participants_created_by_account_id"),
        table_name="meetup_participants",
    )
    op.drop_index(
        op.f("ix_meetup_participants_account_id"), table_name="meetup_participants"
    )
    op.drop_table("meetup_participants")
    op.drop_index(op.f("ix_meetups_created_by_account_id"), table_name="meetups")
    op.drop_table("meetups")
    # ### end Alembic commands ###
