"""participants supersede members

Revision ID: bc71d3e55958
Revises: 1e569d8570b6
Create Date: 2026-08-07 17:44:57.541561

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc71d3e55958"
down_revision: str | Sequence[str] | None = "1e569d8570b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("members")
    op.add_column(
        "meetup_participants", sa.Column("latitude", sa.Float(), nullable=True)
    )
    op.add_column(
        "meetup_participants", sa.Column("longitude", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meetup_participants", "longitude")
    op.drop_column("meetup_participants", "latitude")
    op.create_table(
        "members",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "display_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
    )
    # ### end Alembic commands ###
